### ISSUE TITLE
move data to remote desktop

### ISSUE THREAD

**Issue by mschwentner** [nhmvienna/Workshop_I_Intro_to_Phyloserver#2]
Hi Martin,

at the end of the instructions you have the scp command to move data from the re mote desktop to my PC. I tried the other way around and failed. Can you provide the respective command to move data form my PC to the remoter desktop. IN my case the data is on an external harddrive and the past is:
D:\Pleustiden_Genom\HN00118715
Thanks.
Martin

**Comment by capoony** [comment]
Hi Martin, 

I guess you did not use the flag `-r` to indicate that you want to move the whole folder.

Here are the repective commands to move data (folders) between server and PC:

(1) PC -> Server

`scrp -r D:\Pleustiden_Genom\HN00118715 mschwentner@10.10.0.47:/media/inter/mschwentner`

(2) Server -> PC

`scrp -r mschwentner@10.10.0.47:/media/inter/mschwentner/HN00118715 D:\Pleustiden_Genom`

Hope this helps AND works ;-)

Cheers, Martin

**Comment by mschwentner** [comment]
I get the error 
ssh: Could not resolve hostname d: Name or service not known

is it "scrp" or "scp"?

**Comment by capoony** [comment]
Hi Martin, 

for this to command work you have to run the command in the Powershell of your PC and NOT on the server, since you do not know the IP of your PC and do not define it in the command above. 

However, in the powershell of you PC you can read out your IP by typing `ipconfig`. Using your locla IP address you can accordingly modify the `scp` command from above.

Cheers, Martin

**Comment by capoony** [comment]
Hi Martin, 

awesome that you use the GitHub issues, btw!!! but could you next time start an issue in the [Bioinformatics Support](https://github.com/nhmvienna/BioinformaticsService) repository. This makes it easier to collect all questions in one place ;-)

Cheers, Martin

**Comment by mschwentner** [comment]
works. 
I can do that, I thought you wanted issue in the project where they come up...

**Comment by capoony** [comment]
aweseome!!

yes, agreed. Howver, for more "general" questions (like this one), it may be useful to have them at one place.

Cheers, Martin
